# Generated by Django 5.0 on 2025-12-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pais',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='País'),
        ),
    ]
