# Generated by Django 5.0 on 2025-11-30 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='valor_premio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Estimado del Premio'),
        ),
    ]
