# Generated by Django 5.0 on 2025-11-30 22:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0008_sponsorshiprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerSponsorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_invitacion', models.TextField(help_text='Explica por qué te gustaría que este sponsor participe en tu rifa', verbose_name='Mensaje de Invitación')),
                ('beneficios_ofrecidos', models.TextField(help_text='Qué beneficios ofreces al sponsor (exposición, espacio publicitario, etc.)', verbose_name='Beneficios Ofrecidos')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo')),
                ('propuesta_premio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Premio Propuesto')),
                ('propuesta_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Propuesto')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_a_sponsors_enviadas', to=settings.AUTH_USER_MODEL)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_a_sponsors', to='raffles.raffle')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_patrocinio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Organizador a Sponsor',
                'verbose_name_plural': 'Solicitudes de Organizadores a Sponsors',
                'ordering': ['-fecha_solicitud'],
                'unique_together': {('rifa', 'sponsor')},
            },
        ),
    ]
