# Generated by Django 5.0 on 2025-11-25 04:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='raffles/', verbose_name='Imagen')),
                ('precio_boleto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio por Boleto')),
                ('total_boletos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de Boletos')),
                ('boletos_vendidos', models.IntegerField(default=0, verbose_name='Boletos Vendidos')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('fecha_sorteo', models.DateTimeField(verbose_name='Fecha del Sorteo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('cerrada', 'Cerrada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('premio_principal', models.CharField(max_length=200, verbose_name='Premio Principal')),
                ('descripcion_premio', models.TextField(blank=True, verbose_name='Descripción del Premio')),
                ('imagen_premio', models.ImageField(blank=True, null=True, upload_to='prizes/', verbose_name='Imagen del Premio')),
                ('permite_multiples_boletos', models.BooleanField(default=True, verbose_name='Permitir Múltiples Boletos por Usuario')),
                ('max_boletos_por_usuario', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de Boletos por Usuario')),
            ],
            options={
                'verbose_name': 'Rifa',
                'verbose_name_plural': 'Rifas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleto', models.IntegerField(verbose_name='Número de Boleto')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado'), ('ganador', 'Ganador')], default='reservado', max_length=20, verbose_name='Estado')),
                ('codigo_qr', models.CharField(max_length=100, unique=True, verbose_name='Código QR')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['numero_boleto'],
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sorteo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Sorteo')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
                ('premio_entregado', models.BooleanField(default=False, verbose_name='Premio Entregado')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Ganador',
                'verbose_name_plural': 'Ganadores',
            },
        ),
    ]
