# Generated by Django 5.0 on 2025-11-25 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raffles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rifas_organizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='raffles.raffle'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='winner',
            name='boleto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premio_ganado', to='raffles.ticket'),
        ),
        migrations.AddField(
            model_name='winner',
            name='rifa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ganador', to='raffles.raffle'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('rifa', 'numero_boleto')},
        ),
    ]
