# Generated by Django 5.0 on 2025-11-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0003_raffle_valor_premio'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='fecha_pausa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pausa'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='motivo_pausa',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Pausa'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='nueva_fecha_sorteo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nueva Fecha de Sorteo (Extensión)'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='revision_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Revisión del Administrador'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('pausada', 'Pausada - En Revisión'), ('cerrada', 'Cerrada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
    ]
