# Generated by Django 5.0 on 2025-11-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0004_raffle_fecha_pausa_raffle_fecha_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='documento_legal',
            field=models.FileField(blank=True, help_text='Sube el documento que autoriza la realización de esta rifa (PDF, Word, imagen)', null=True, upload_to='documentos_legales/', verbose_name='Documento de Autorización Legal'),
        ),
    ]
