# Generated by Django 5.0 on 2025-11-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0005_add_documento_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='acta_digital',
            field=models.TextField(blank=True, help_text='Registro completo y auditable del sorteo', null=True, verbose_name='Acta Digital del Sorteo'),
        ),
        migrations.AddField(
            model_name='winner',
            name='algoritmo',
            field=models.CharField(default='SHA256+Timestamp', max_length=50, verbose_name='Algoritmo Utilizado'),
        ),
        migrations.AddField(
            model_name='winner',
            name='hash_verificacion',
            field=models.CharField(blank=True, help_text='Hash SHA256 de toda la información del sorteo', max_length=64, null=True, verbose_name='Hash de Verificación'),
        ),
        migrations.AddField(
            model_name='winner',
            name='participantes_totales',
            field=models.IntegerField(blank=True, help_text='Número de boletos pagados al momento del sorteo', null=True, verbose_name='Total de Participantes'),
        ),
        migrations.AddField(
            model_name='winner',
            name='seed_aleatorio',
            field=models.CharField(blank=True, help_text='Hash SHA256 usado como semilla para el sorteo', max_length=64, null=True, verbose_name='Semilla Aleatoria (SHA256)'),
        ),
        migrations.AddField(
            model_name='winner',
            name='timestamp_sorteo',
            field=models.BigIntegerField(blank=True, help_text='Unix timestamp exacto del momento del sorteo', null=True, verbose_name='Timestamp del Sorteo'),
        ),
    ]
