# Generated by Django 5.0 on 2025-11-30 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0006_add_sorteo_verificable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='comentarios_revision',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios de la Revisión'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='fecha_revision_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='fecha_solicitud',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Solicitud de Aprobación'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifas_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_aprobacion', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('activa', 'Activa'), ('pausada', 'Pausada - En Revisión'), ('cerrada', 'Cerrada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
    ]
