# Generated by Django 5.0 on 2025-11-30 22:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0007_add_sistema_aprobacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_premio_adicional', models.CharField(max_length=200, verbose_name='Nombre del Premio Adicional')),
                ('descripcion_premio', models.TextField(verbose_name='Descripción del Premio')),
                ('valor_premio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor del Premio')),
                ('imagen_premio', models.ImageField(upload_to='sponsor_prizes/', verbose_name='Imagen del Premio')),
                ('nombre_marca', models.CharField(max_length=200, verbose_name='Nombre de la Marca')),
                ('logo_marca', models.ImageField(upload_to='sponsor_logos/', verbose_name='Logo de la Marca')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('mensaje_patrocinio', models.TextField(help_text='Breve mensaje sobre por qué quieres patrocinar esta rifa', verbose_name='Mensaje de Patrocinio')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_patrocinio', to='raffles.raffle')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_patrocinio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Patrocinio',
                'verbose_name_plural': 'Solicitudes de Patrocinio',
                'ordering': ['-fecha_solicitud'],
                'unique_together': {('rifa', 'sponsor', 'estado')},
            },
        ),
    ]
