# Generated by Django 5.0 on 2025-12-04 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0009_organizersponsorrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sponsorshiprequest',
            unique_together=set(),
        ),
    ]
