# Generated by Django 5.0 on 2025-11-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo')], max_length=20, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('transaction_id', models.CharField(max_length=200, unique=True, verbose_name='ID de Transacción')),
                ('payment_intent_id', models.CharField(blank=True, max_length=200, verbose_name='Payment Intent ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('notas_admin', models.TextField(blank=True, verbose_name='Notas del Administrador')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Reembolsado')),
                ('razon', models.TextField(verbose_name='Razón del Reembolso')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesado')),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('completado', 'Completado')], default='solicitado', max_length=20)),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
            },
        ),
    ]
