# Generated by Django 5.0 on 2025-11-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('raffles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='boletos',
            field=models.ManyToManyField(related_name='pagos', to='raffles.ticket'),
        ),
    ]
