# Generated by Django 5.0 on 2025-12-01 11:11

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra de Boleto'), ('ganador', 'Ganador de Rifa'), ('sorteo', 'Sorteo Realizado'), ('cancelacion', 'Rifa Cancelada'), ('nuevo_organizador', 'Nueva Rifa Disponible'), ('recordatorio', 'Recordatorio de Sorteo'), ('sistema', 'Notificación del Sistema'), ('sponsor_aprobado', 'Sponsor Aprobado'), ('sponsor_rechazado', 'Sponsor Rechazado'), ('rifa', 'Rifa')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ciudad',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='codigo_postal',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='direccion',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='estado',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='Teléfono'),
        ),
    ]
