# Generated by Django 5.0 on 2025-12-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('eliminar_usuario', 'Eliminar Usuario'), ('eliminar_rifa', 'Eliminar Rifa'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('compra', 'Compra'), ('pago', 'Pago'), ('sorteo', 'Sorteo'), ('sorteo_manual', 'Sorteo Manual'), ('aprobar_sponsor', 'Aprobar Sponsor'), ('rechazar_sponsor', 'Rechazar Sponsor'), ('cambiar_rol', 'Cambiar Rol'), ('suspender_usuario', 'Suspender Usuario'), ('activar_usuario', 'Activar Usuario'), ('cancelar_rifa', 'Cancelar Rifa'), ('cancelar_rifa_con_reembolsos', 'Cancelar Rifa con Reembolsos'), ('reembolso', 'Reembolso'), ('reembolso_automatico', 'Reembolso Automático'), ('error_reembolso', 'Error en Reembolso'), ('extender_plazo', 'Extender Plazo'), ('aprobar_sorteo_parcial', 'Aprobar Sorteo Parcial'), ('aprobar_rifa', 'Aprobar Rifa'), ('rechazar_rifa', 'Rechazar Rifa')], max_length=50, verbose_name='Acción'),
        ),
    ]
