# Generated by Django 5.0 on 2025-11-30 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='motivo',
            field=models.CharField(choices=[('duplicado', 'Pago Duplicado'), ('cancelacion', 'Cancelación de Rifa'), ('error_sistema', 'Error del Sistema'), ('solicitud_usuario', 'Solicitud del Usuario'), ('fraude', 'Sospecha de Fraude'), ('otro', 'Otro Motivo')], default='otro', max_length=50, verbose_name='Motivo del Reembolso'),
        ),
        migrations.AddField(
            model_name='refund',
            name='procesado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos_procesados', to=settings.AUTH_USER_MODEL, verbose_name='Procesado Por'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='razon',
            field=models.TextField(verbose_name='Explicación Detallada'),
        ),
    ]
