# Generated by Django 5.0 on 2025-12-04 03:09

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_refund_motivo_refund_procesado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_intent_id',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=400, verbose_name='Payment Intent ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=apps.core.fields.EncryptedCharField(max_length=400, unique=True, verbose_name='ID de Transacción'),
        ),
    ]
